/*
 * Central icon exports keep naming and library choice consistent across the UI.
 * To add an icon, re-export its Lucide component here and consume the alias from
 * feature components instead of importing different icon libraries per page.
 */
export {
  Archive as ArchiveIcon,
  Activity as ActivityIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Check as CheckIcon,
  ChevronRight as ChevronRightIcon,
  ClipboardList as ClipboardListIcon,
  Clock3 as ClockIcon,
  CalendarDays as CalendarIcon,
  BadgeCheck as BadgeCheckIcon,
  Bell as BellIcon,
  Banknote as MoneyIcon,
  BriefcaseBusiness as BriefcaseIcon,
  CircleAlert as AlertIcon,
  Droplets as BloodIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  LayoutDashboard as DashboardIcon,
  FileText as FileTextIcon,
  FileCheck2 as FileCheckIcon,
  HeartPulse as HeartPulseIcon,
  Languages as LanguagesIcon,
  LogIn as LogInIcon,
  LogOut as LogOutIcon,
  Menu as MenuIcon,
  Moon as MoonIcon,
  MapPin as MapPinIcon,
  Phone as PhoneIcon,
  Pill as PillIcon,
  Pencil as PencilIcon,
  Plus as PlusIcon,
  RefreshCw as RefreshIcon,
  Save as SaveIcon,
  ShoppingBasket as ShoppingBasketIcon,
  Send as SendIcon,
  Search as SearchIcon,
  Star as StarIcon,
  MessageSquareText as MessageIcon,
  Flag as FlagIcon,
  ShieldCheck as ShieldCheckIcon,
  Sparkles as InsightsIcon,
  Stethoscope as StethoscopeIcon,
  Sun as SunIcon,
  Trash2 as TrashIcon,
  Utensils as UtensilsIcon,
  UserPlus as UserPlusIcon,
  UserRound as UserIcon,
  UploadCloud as UploadIcon,
  UsersRound as UsersIcon,
  X as CloseIcon,
} from "lucide-react";
